# Generated by Django 4.2.20 on 2025-05-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Користувач з таким логіном вже існує.'}, help_text='Необхідно. 150 символів або менше. Літери, цифри та @/./+/-/_ лише.', max_length=150, unique=True, verbose_name='Логін'),
        ),
    ]
