# Generated by Django 4.2.20 on 2025-05-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
