# Generated by Django 4.2.20 on 2025-04-13 17:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Зображення категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва підкатегорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory_images/', verbose_name='Зображення підкатегорії')),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='description_images/', verbose_name='Зображення для розширеного опису')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='goods.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
                'db_table': 'subcategory',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('strength_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Клас міцності')),
                ('coating', models.CharField(blank=True, max_length=100, null=True, verbose_name='Покриття')),
                ('diameters', models.CharField(blank=True, max_length=255, null=True, verbose_name='Діаметр, мм')),
                ('cuts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Крок нарізі, мм')),
                ('lengths', models.CharField(blank=True, max_length=255, null=True, verbose_name='Довжина, мм')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('batch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Партія')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Зображення товару')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний товар')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.subcategory', verbose_name='Підкатегорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'product',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_search__4bea98_gin'), django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_gin_idx', opclasses=['gin_trgm_ops']), models.Index(fields=['code'], name='product_code_241a57_idx'), models.Index(fields=['price'], name='product_price_d2c05d_idx')],
            },
        ),
    ]
