# Generated by Django 4.2.20 on 2025-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Створено'), (1, 'Оплачено'), (2, 'В дорозі'), (3, 'Доставлено'), (4, 'Скасовано')], default=0, verbose_name='Статус заказа'),
        ),
    ]
