# Generated by Django 4.2.20 on 2025-05-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основний",
                        help_text="Назва для ідентифікації цього набору налаштувань",
                        max_length=100,
                        verbose_name="Назва налаштування",
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        blank=True,
                        help_text="Вкажіть email-адреси для отримання повідомлень. Кожну адресу з нового рядка.",
                        verbose_name="Email для повідомлень",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Увімкнути або вимкнути відправку повідомлень",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
            ],
            options={
                "verbose_name": "Налаштування повідомлень",
                "verbose_name_plural": "Налаштування повідомлень",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ("id",),
                "verbose_name": "Елемент замовлення",
                "verbose_name_plural": "Елементи замовлення",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адреса доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Прізвище"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_on_get",
            field=models.BooleanField(
                default=False, verbose_name="Оплата при отриманні"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="requires_delivery",
            field=models.BooleanField(default=True, verbose_name="Потрібна доставка"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Створено"),
                    (1, "Оплачено"),
                    (2, "В дорозі"),
                    (3, "Доставлено"),
                    (4, "Скасовано"),
                ],
                default=0,
                verbose_name="Статус замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Кількість"),
        ),
    ]
