# Generated by Django 4.2.20 on 2025-05-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_emailnotificationsettings_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailnotificationsettings",
            options={
                "verbose_name": "Email для повідомлень",
                "verbose_name_plural": "Emails для повідомлень",
            },
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_name = 'orders_emailnotificationsettings' AND column_name = 'name'
                ) THEN
                    ALTER TABLE orders_emailnotificationsettings DROP COLUMN name CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="emailnotificationsettings",
            name="email",
            field=models.EmailField(
                help_text="На цей email будуть надсилатися повідомлення про нові замовлення",
                max_length=254,
                verbose_name="Email для повідомлень",
            ),
        ),
    ]
