# Generated by Django 4.2.20 on 2025-05-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_emailnotificationsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotificationsettings',
            name='name',
        ),
    ]
