# Generated by Django 4.2.20 on 2025-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_emailnotificationsettings_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotificationsettings',
            options={'verbose_name': 'Налаштування повідомлень', 'verbose_name_plural': 'Налаштування повідомлень'},
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='name',
            field=models.CharField(default='Основний', help_text='Назва для ідентифікації цього набору налаштувань', max_length=100, verbose_name='Назва налаштування'),
        ),
        migrations.AlterField(
            model_name='emailnotificationsettings',
            name='email',
            field=models.TextField(blank=True, help_text='Вкажіть email-адреси для отримання повідомлень. Кожну адресу з нового рядка.', verbose_name='Email для повідомлень'),
        ),
    ]
