# Generated by Django 4.2.20 on 2025-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_emailnotificationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='email_signature',
            field=models.TextField(blank=True, default='З повагою,\nКоманда інтернет-магазину', help_text='Підпис, який буде додано в кінці листа', verbose_name='Підпис в листі'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='email_subject_template',
            field=models.CharField(default='Нове замовлення №{order_id}', help_text='Шаблон теми листа. Використовуйте {order_id} для номера замовлення', max_length=200, verbose_name='Шаблон теми листа'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='sender_email',
            field=models.EmailField(default='noreply@example.com', help_text='Email, від імені якого будуть відправлятися повідомлення', max_length=254, verbose_name='Email відправника'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Пароль для авторизації на SMTP-сервері або пароль додатку', max_length=100, verbose_name='Пароль SMTP'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='Порт SMTP-сервера (зазвичай 25, 465 або 587)', verbose_name='SMTP порт'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', help_text='Адреса SMTP-сервера для відправки листів', max_length=100, verbose_name='SMTP сервер'),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='smtp_username',
            field=models.CharField(blank=True, help_text="Ім'я користувача для авторизації на SMTP-сервері (зазвичай це email)", max_length=100, verbose_name="Ім'я користувача SMTP"),
        ),
        migrations.AddField(
            model_name='emailnotificationsettings',
            name='use_tls',
            field=models.BooleanField(default=True, help_text="Використовувати захищене з'єднання TLS", verbose_name='Використовувати TLS'),
        ),
    ]
