# Generated by Django 4.2.20 on 2025-05-09 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_product_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_emailnotificationsettings_email_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                help_text="Формат: порядковый_номер_за_день.DDMMYY",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Номер заказа",
            ),
        ),
    ]
