# Generated by Django 4.2.20 on 2025-05-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart'),
    ]

    operations = [
    ]
