# Generated by Django 4.2.20 on 2025-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20250509_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_reserved',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, были ли зарезервированы товары', verbose_name='Товари зарезервовані'),
        ),
    ]
