# Generated by Django 4.2.20 on 2025-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_products_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Оплата при отриманні'), ('bank', 'Оплата на розрахунковий рахунок підприємства')], default='cash', max_length=10, verbose_name='Спосіб оплати'),
        ),
    ]
