# Generated by Django 4.2.20 on 2025-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_remove_order_payment_on_get_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Оплата картою"),
                    ("cash", "Готівкою/картою при отриманні"),
                    ("bank", "Оплата на розрахунковий рахунок підприємства"),
                ],
                default="card",
                max_length=10,
                verbose_name="Спосіб оплати",
            ),
        ),
    ]
